- apps/sps-termportal-web/components/ButtonScrollTop.vue
- apps/sps-termportal-web/components/WelcomeTP.vue
- apps/sps-termportal-web/locales/en.json
- apps/sps-termportal-web/pages/[samling]/[...id].vue
- apps/sps-termportal-web/pages/[samling]/index.vue
- apps/sps-termportal-web/pages/index.vue
- apps/sps-termportal-web/pages/innstillinger.vue
- apps/sps-termportal-web/pages/om.vue
- apps/sps-termportal-web/pages/search.vue
> fix(tp): localization

- apps/sps-termportal-web/pages/[samling]/[...id].vue
- apps/sps-termportal-web/pages/search.vue
> Fix handling of fbk concepts

- apps/sps-termportal-web/utils/compactData.ts
- apps/sps-termportal-web/utils/genConceptQuery.ts
- apps/sps-termportal-web/utils/genSamlingQuery.ts
[vercel skip chc-*]
[vercel skip api]
[vercel skip ub-urls]
> fix(tp): use shorter abbrev for dcterms and add xsd

- apps/sps-termportal-web/utils/vars-termbase.ts
> fix(tp): move uhr to okonAdmin

- apps/sps-termportal-web/pages/[samling]/[...id].vue
- apps/sps-termportal-web/utils/compactData.ts
fix(tp): use id of object display domain string
> fix(tp): compact domene info with type id

- apps/sps-termportal-web/locales/en.json
- apps/sps-termportal-web/locales/nb.json
- apps/sps-termportal-web/locales/nn.json
- apps/sps-termportal-web/pages/[termbase]/[...id].vue
Add Note to RTT and NOT that termbases are not maintained
> Feat tp add note to historical termbases

- apps/sps-termportal-web/package.json
- package-lock.json
> feat(tp): upgrade nuxt

- apps/sps-termportal-web/locales/en.json
- apps/sps-termportal-web/locales/nb.json
- apps/sps-termportal-web/locales/nn.json
- apps/sps-termportal-web/server/utils/genSearchQuery.ts
- apps/sps-termportal-web/server/utils/genSearchQueryAll.ts
- apps/sps-termportal-web/utils/vars-termbase.ts
Combined MRT and MRT2 in the wiki.
Remove MRT2 as termbase option in frontend.
> Fix #tp remove mrt2

- apps/sps-termportal-web/package.json
- package-lock.json
Install sass for primevue customization
> feat(tp): add sass

- apps/sps-termportal-web/server/utils/genSearchQuery.ts
Final fix should be custom highlighting.
> fix(tp): remove trailing dot from sanitized search string

- apps/sps-termportal-web/app.vue
- apps/sps-termportal-web/assets/tp-theme/theme.scss
- apps/sps-termportal-web/components/AutoComplete.vue
- apps/sps-termportal-web/components/BaseAutoComplete.vue
- apps/sps-termportal-web/components/SearchField.vue
- apps/sps-termportal-web/composables/states.ts
- apps/sps-termportal-web/composables/useAutoCompleteSuggestions.ts
- apps/sps-termportal-web/composables/useSearchHistory.ts
- apps/sps-termportal-web/pages/[termbase]/[...id].vue
- apps/sps-termportal-web/plugins/primevue.ts
- apps/sps-termportal-web/server/utils/genAutocompleteQuery.ts
- autocomplete from
- search history
- matches
> Feat #tp autocomplete searchbar

- apps/sps-termportal-web/locales/en.json
- apps/sps-termportal-web/locales/nb.json
- apps/sps-termportal-web/locales/nn.json
- apps/sps-termportal-web/server/utils/genSearchQuery.ts
- apps/sps-termportal-web/utils/vars-termbase.ts
- localization
- termbase data
> feat(tp): add semantics termbase data

- apps/sps-termportal-web/components/SearchFilter.vue
- apps/sps-termportal-web/components/TermDescription.vue
- apps/sps-termportal-web/components/TermProp.vue
- apps/sps-termportal-web/locales/en.json
- apps/sps-termportal-web/locales/nb.json
- apps/sps-termportal-web/locales/nn.json
- apps/sps-termportal-web/pages/[termbase]/[...id].vue
- apps/sps-termportal-web/pages/om.vue
- apps/sps-termportal-web/utils/vars.ts
- adapt concept display to UD data
- mainly presence of multiple notes, refs
- reified notes
- fix about data display
> Fix #tp ud data display

- apps/sps-ordbokene-web/app.vue
- apps/sps-ordbokene-web/components/AdvancedSearchForm.vue
- apps/sps-ordbokene-web/components/Autocomplete.vue
- apps/sps-ordbokene-web/components/SearchForm.vue
a11y changes tested with screen reader user.
> Test #ob blur input

- apps/sps-termportal-web/components/HeaderSearchDomains.vue
- apps/sps-termportal-web/components/SubdomainEntry.vue
- apps/sps-termportal-web/pages/innstillinger.vue
- fix sizes of subdomain checkboxes
- topalign subdomain checkboxes
- reduce size of minor cbs
> Fix size and alignment of checkboxes

- apps/sps-ordbokene-web/package.json
- package-lock.json
- uninstall nuxt dev in ordbøkene
- package-lock wasn't synced with ob's package.json
> fix: uninstall nuxt dev sync pgk lock for ob

- apps/experimental-api/docker-compose.yml
This includes changes in #116 done by @wruiwr
> add container_name to services

- apps/docs/pages/docs/monorepo.mdx
- apps/docs/styles/globals.css
Add documentation for
- installing/uninstalling packages in the monorepo
- using tag feature with build ignore step
> Feat #docs extend monorepo docs

- apps/sps-termportal-web/composables/usePushSearchOptionsToRoute.ts
- apps/sps-termportal-web/pages/search.vue
- apps/sps-termportal-web/utils/vars.ts
Properly sync searchinterface setting with route:
- termbase selection
- useDomain setting
> fix rout param sync for termbases and useDomain setting

- apps/sps-termportal-web/locales/nb.json
- apps/sps-termportal-web/locales/nn.json
- reverting RTT and NOT comment
- Too much of a judgement to say they have value on every termpost
> fix(tp): revert historical termbase comment

- apps/sps-ordbokene-web/assets/css/tailwind.css
- apps/sps-ordbokene-web/components/AdvancedResults.vue
- apps/sps-ordbokene-web/components/Article.vue
- apps/sps-ordbokene-web/components/ArticleFooter.vue
- apps/sps-ordbokene-web/components/ArticleHeader.vue
- apps/sps-ordbokene-web/components/Definition.vue
- apps/sps-ordbokene-web/components/Example.vue
- apps/sps-ordbokene-web/components/Inflection/Table.vue
- apps/sps-ordbokene-web/components/Inflection/inflectionRowParticiple.vue
- apps/sps-ordbokene-web/components/Inflection/inflectionRowsVerb.vue
- apps/sps-ordbokene-web/components/SuggestResults.vue
- apps/sps-ordbokene-web/utils/helpers.ts
Added notranslate and lang tags
Added content_locale prop that later can replace the language prop
> Fix #ob lang tags

- apps/sps-ordbokene-web/components/Header.vue
- apps/sps-ordbokene-web/components/Inflection/Table.vue
- apps/sps-ordbokene-web/components/Inflection/inflectionRowNoun.vue
- apps/sps-ordbokene-web/components/Inflection/mixins/ordbankUtils.js
- apps/sps-ordbokene-web/locales/eng.json
- apps/sps-ordbokene-web/locales/nno.json
- apps/sps-ordbokene-web/locales/nob.json
- apps/sps-ordbokene-web/locales/ukr.json
- apps/sps-ordbokene-web/plugins/primevue.ts
~- Added a nav item("Text-Size") for the accessibility.~
- Updated the inflection table
> upd-#ob-inflection-table-&-header

- apps/sps-ordbokene-web/components/Inflection/mixins/ordbankUtils.js
Issue: Error on rendering inflection table e.g. /bm/11072
> hot fix inflection table

- apps/sps-termportal-admin/app.vue
- apps/sps-termportal-admin/components/NavBar.vue
- don't display full navbar on landing page
- display scroll bar on landing page
> feat(tpa): minimize navbar and fix scroll bar display

- apps/sps-termportal-admin/package.json
- package-lock.json
- remove ordbokene-nuxt from package lock
- reinstall nuxt/content
- downgrade nuxt/content to 2.7
- 2.8+ has a problem with incompatible dependencies
> fix build error caused by missing dependencies

- apps/ub-dashboard/src/app/(dashboard)/groups/_components/group.tsx
- apps/ub-dashboard/src/app/(dashboard)/persons/_components/person.tsx
- apps/ub-dashboard/src/app/(dashboard)/persons/_components/skills.tsx
- apps/ub-dashboard/src/app/(dashboard)/projects/_components/project.tsx
- apps/ub-dashboard/src/app/(dashboard)/timeline/page.tsx
- apps/ub-dashboard/src/components/date.tsx
- apps/ub-dashboard/src/components/timeline.tsx
- apps/ub-dashboard/src/types/index.ts
Update group query and skills component
Update timeline page and add query
> Add dateToString function and update types

- apps/sps-termportal-admin/components/ExploreDefinitions.vue
- apps/sps-termportal-admin/components/InsightInstitutions.vue
- apps/sps-termportal-admin/components/InsightPeople.vue
- apps/sps-termportal-admin/nuxt.config.ts
- apps/sps-termportal-admin/package.json
- apps/sps-termportal-admin/pages/insights/index.vue
- apps/sps-termportal-admin/sanity.config.ts
- apps/sps-termportal-admin/sanity/deskStructure/index.js
- package-lock.json
- add people, institutions insights
- add backreference plugin
- add vision plugin
> Feat #tpa add stat overviews

- apps/sps-termportal-web/pages/[termbase]/[...id].vue
- apps/sps-termportal-web/pages/om.vue
- packages/termportal-ui/utils/vars.ts
- rm Vetle from members
- hide modified on legacy termbases
- introduce global variables in ui pkg
> Fix #tpw update members hide legacy data

- apps/sps-termportal-admin/pages/docs/index.vue
- add and fix heading styles for nuxt content data
> feat(tpa): add styles for content docs

- apps/sps-termportal-web/pages/index.vue
- apps/sps-termportal-web/pages/om.vue
- headings are not updated when changing locale
- key in heading component doesn't fix anything
- key on ContentDoc forces rerendering
> Headings rendered by nuxt content don't rerender when changing locale

- apps/sps-termportal-admin/pages/overview/index.vue
- apps/sps-termportal-admin/sanity/schemas/activity.js
- apps/sps-termportal-admin/sanity/schemas/props/index.js
- fix keys for overview display of members, activities
- switch notes to portable text
> Feat #tpa notes port text display

- apps/sps-termportal-web/components/TermDescription.vue
- apps/sps-termportal-web/server/utils/parseConceptData.ts
- apps/sps-termportal-web/utils/utils.ts
- Some FBK data used multiple definitions on one definition object
- fix: add preprocessing
> Fix #tpw display of multiple defs object

- apps/sps-termportal-admin/components/RecentActivities.vue
- apps/sps-termportal-admin/layouts/default.vue
- apps/sps-termportal-admin/pages/activities/index.vue
- apps/sps-termportal-admin/pages/index.vue
- packages/termportal-ui/components/NavBarLink.vue
- reorder expanded activity data
- display recent activities on landing page
- make navbar link more visible
> Feat #tpa improve activity data display

- apps/sps-termportal-admin/components/ToC.vue
- apps/sps-termportal-admin/components/ToCList.vue
- apps/sps-termportal-admin/pages/docs/index.vue
- packages/termportal-ui/components/AppLinkText.vue
- Add ToC components
- Add toc to docs page
> Feat #tpa add toc to docs

- apps/sps-termportal-web/components/NewsEntry.vue
- apps/sps-termportal-web/components/NewsWrapper.vue
- fix key for news sorting
- move link target handling to news item component
> Fix #tpw news display

- apps/sps-termportal-admin/components/ExploreDefinitions.vue
- apps/sps-termportal-admin/components/SimpleDomainOverview.vue
- apps/sps-termportal-admin/pages/explore/domain.vue
- apps/sps-termportal-admin/utils/utils.ts
- packages/termportal-ui/assets/tp-theme/theme.scss
- add numbers and aggregation to overview
- Add domain selection to overview
- fix spacing of overview
- move explore tb to folder
> Feat #tpa extend domain quality info

- apps/sps-termportal-web/composables/useAutoCompleteSuggestions.ts
- apps/sps-termportal-web/composables/useGenSearchOptions.ts
- apps/sps-termportal-web/nuxt.config.ts
- apps/sps-termportal-web/server/api/search/autocomplete.ts
- apps/sps-termportal-web/server/utils/genQueryUtils.ts
- pass search options as query params
- optimize passing of options
- add caching
> Feat #tpw add caching to autocomplete

- apps/sps-termportal-web/components/termpost/Base.vue
- apps/sps-termportal-web/composables/useFetchSearchData.ts
- mathjax call in component
- filter reset on option change
> Fix #tpw mathjax call

- Dockerfile.api
revise Dockerfile.api for bun setup
> revise Dockerfile.api for bun

- .github/workflows/cicd-deploy-hono-api-dev.yaml
- microk8s-hono-api/base/config.yaml
- microk8s-hono-api/base/deployment.yaml
- microk8s-hono-api/base/ingress.yaml
- microk8s-hono-api/base/kustomization.yaml
- microk8s-hono-api/base/service.yaml
- microk8s-hono-api/dev/config.yaml
- microk8s-hono-api/dev/deployment.yaml
- microk8s-hono-api/dev/ingress.yaml
- microk8s-hono-api/dev/kustomization.yaml
- microk8s-hono-api/dev/namespace.yaml
- microk8s-hono-api directory includes code for deployment of honor api to microk8s Kubernetes cluster on NREC
- GitHub actions are implemented in .github/workflows/ for this deployment
> Setup hono api kubernetes deployment

- .github/workflows/cicd-deploy-hono-api-dev.yaml
- .github/workflows/cicd-deploy-hono-api-prod.yaml
- .github/workflows/cicd-deploy-hono-api-test.yaml
- Dockerfile.api
- docker-compose.api.yml
- microk8s-hono-api/base/ingress.yaml
- microk8s-hono-api/dev/config.yaml
- microk8s-hono-api/dev/ingress.yaml
- microk8s-hono-api/prod/config.yaml
- microk8s-hono-api/prod/deployment.yaml
- microk8s-hono-api/prod/ingress.yaml
- microk8s-hono-api/prod/kustomization.yaml
- microk8s-hono-api/prod/namespace.yaml
- microk8s-hono-api/test/config.yaml
- microk8s-hono-api/test/deployment.yaml
- microk8s-hono-api/test/ingress.yaml
- microk8s-hono-api/test/kustomization.yaml
- microk8s-hono-api/test/namespace.yaml
Main work:
1. add implementation of resources `test` overlay and its Github actions  workflow for the deployment of hono API to test env/namespace of Kubernetes cluster on NREC
2. add implementation of resources `prod` overlay and its Github actions  workflow for the deployment of hono API to prod env/namespace of Kubernetes cluster on NREC
> hono api development to mircok8s kubernetes on NREC

- apps/sps-termportal-admin/sanity/schemas/termbase.js
Add fields to planing data to enable better statistics reporting:
- topdomain
- size
> feat(tpa): add topdomain and size to planning data

- apps/sps-termportal-web/pages/innstillinger.vue
- apps/sps-termportal-web/utils/analyticsEvents.ts
Add event to track termpost display languages
> Feat #tpw add settings event

- apps/sps-termportal-admin/components/ActivitiesOverview.vue
- apps/sps-termportal-admin/components/TermbaseActivities.vue
- apps/sps-termportal-admin/components/TermbaseOverview.vue
- apps/sps-termportal-admin/components/TermgroupMembers.vue
- apps/sps-termportal-admin/components/dashboard/OngoingActivities.vue
- apps/sps-termportal-admin/components/dashboard/RecentActivities.vue
- apps/sps-termportal-admin/components/dashboard/ScheduledActivities.vue
- apps/sps-termportal-admin/components/dashboard/ScheduledMemberUpdate.vue
- apps/sps-termportal-admin/pages/index.vue
- apps/sps-termportal-admin/sanity/schemas/activity.js
- apps/sps-termportal-admin/utils/constants.ts
- apps/sps-termportal-admin/utils/utils.ts
Add activity types:
- status report
- member update
Add display of activity data
> Feat #tpa add support for status updates

- apps/sps-termportal-admin/components/TermbaseOverview.vue
- apps/sps-termportal-admin/components/dashboard/OngoingActivities.vue
- apps/sps-termportal-admin/components/dashboard/RecentActivities.vue
- apps/sps-termportal-admin/pages/index.vue
- apps/sps-termportal-admin/server/utils/genOverviewQuery.ts
- apps/sps-termportal-web/locales/nn.json
- nn typo
- spacing, placement dashboard
- handling of ongoing activities in reminder section
> Fix #tpa minor fixes

- apps/sps-termportal-web/components/termpost/Base.vue
- apps/sps-termportal-web/components/termpost/VisualizationSection.vue
- apps/sps-termportal-web/utils/utils.ts
- fix rendering problem with displayTitle composable
- fix localization of image caption
> Fix #tpw image caption locale handling

- apps/docs/pages/docs/monorepo.mdx
I left the list of tags untouched for other applications thatn stadnamn-web
> update ignore build step documentation

- apps/sps-termportal-admin/nuxt.config.ts
- apps/sps-termportal-admin/turbo.json
- Register Sanity token and project id in turbo.json
- Move project id to env
> fix(tpa): register sanity project it and token, move to ENV

- apps/sps-termportal-web/nuxt.config.ts
- apps/sps-termportal-web/pages/tb/[termbase]/index.vue
Disable SSR for routes. Investigate when upgrading nuxt version etc.
> fix(tpw): tmp: disable ssr for routes until further investigation

- apps/sps-termportal-admin/components/TermbaseOverview.vue
Only trigger navigation when on a text field and if the tb has an ID
> fix(tpa): add check for target and tb id
